spring:
  datasource:
    url: jdbc:h2:mem:sdb2023
    username: sdb2023
    password:
  jpa:
    show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | upadate | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false